from pathlib import Path

DATA_DIR = Path("/path/to/your/images")
CHECKPOINT_DIR = Path("checkpoints")
CHECKPOINT_PATH = CHECKPOINT_DIR / "latest.pt"

IMAGE_SIZE = 256
BATCH_SIZE = 8
NUM_WORKERS = 6
VALIDATION_SPLIT = 0.02

LEARNING_RATE = 1e-4
LAMBDA = 0.010
MAX_STEPS = 15000
GRAD_CLIP = 1.0

LOG_EVERY = 20
PREVIEW_EVERY = 250
SAVE_EVERY = 500
VALIDATION_BATCHES = 8
SEED = 42
